### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFDefault#4]
Depends on

- [x] zopefoundation/Products.CMFCore#23
- [x] zopefoundation/Products.GenericSetup#47
- [x] zopefoundation/Products.MailHost#5

**Comment by Themanwithoutaplan** [comment]
I can't currently get trunk to run happily with Zope 4, though the PyPI release will.
